language: perl

matrix:
  include:
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'

  notifications:
  email: false
  slack:
    secure: eBm4COP/oWX2wDozaF64Ectp+HfkjtzF7v0U9W433QUsQPxrufsNv7ZJFeKrkaS25SIjEgknYn/4yZYyJCadQUm7LsKAmJYNbVIPvJ1veEubWhRVpCS3juLH0/5UGQT8a7QudyMOmvJ0QkiBtvAXH95Ir7RBsQgKtjrtYeQT/mOP1RBNr22MJGm5pIa0M80AcM1BveCTt5MJqqoO7u0sg+LT2v0epi7nf0XCrYfnI63/P0bRNeEUxzeRhJOB9BxzKQk3NzGaxdiuDl1rKSFp1PyxNirMkC4jusOyQR10MikNP2DDeq4yFdRZYlpbFuUWZhZlSorOl8oINw2/CcaN2II0NLie+ejBUHoLdDFpjhqU9ZeSlDX4hyQ2WRGRuYAnn2bbUxUU1sg57tGbaLMqhWYhXCQ6nNty4OqmIBgmaMUGGeduF6AMkz86JJ821nhaZLvKZuKDhPy7rRdeZ5Bx3i3zc6Vv9Qdy0Zv1hSX3sHif4mQN0zv21mQVvG3YaSF2xQ+lN2JZPfm61qB8wkzB2WjWDSwvOJs/AxOBtftxf+8ZC1CTxE30lcXBYrLvcBW5paK3NFSt3Nzm7ScfZ51AKvfv4PaGJUchVkgaAlXO+C5Fsg2y6TSKtrCnCad5XQ1scEMpZAsJ4WCPcpFMwUhA97ziVeM7Rx/vMs8vs6CX4WQ=
